#!/usr/bin/env bash

pushd ~/repos/dev/env/.config/nvim
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/repos/dev/tmux-sessionizer/
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/repos/dev
git add .
git commit -m 'automated dev commit'
git push
popd

