#!/usr/bin/env bash

## Apt
## https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

sudo pacman -Syu
sudo pacman -S docker docker-compose
sudo groupadd docker
sudo usermod -aG docker $USER

