#!/usr/bin/env bash
sudo pacman -Syu --no-confirm

if ! command -v git &> /dev/null; then
    sudo pacman -S git --no-confirm
fi

if [ ! -d $HOME/repos ]; then
    mkdir $HOME/repos
fi

git clone https://github.com/lauhkz/dev $HOME/repos/dev

pushd $HOME/repos/dev
./run
popd
