#!/usr/bin/env bash
sudo pacman -Syu --noconfirm

if ! command -v git &> /dev/null; then
    sudo pacman -S git --noconfirm
fi

# Installing Paru
git clone https://aur.archlinux.org/paru.git $HOME/paru
cd $HOME/paru
makepkg -si --noconfirm
cd $HOME
rm -rf paru

if [ ! -d $HOME/repos ]; then
    mkdir $HOME/repos
fi

if [ ! -d $HOME/repos/dev ]; then
	git clone https://github.com/lauhkz/dev $HOME/repos/dev
fi

pushd $HOME/repos/dev
./run
popd



